### ISSUE TITLE
Laravel 7 support, missing `HttpauthServiceProviderLaravel7.php`

### ISSUE THREAD

**Issue by edalzell** [Intervention/httpauth#6]
When using the just released Laravel 7, there are errors during the composer step due to a missing file `HttpauthServiceProviderLaravel7.php`

**Comment by olivervogel** [comment]
Using version >=3.0.0 should work. Auto discover should load the ServiceProvider, just publish the config with `php artisan vendor:publish`.

```php
Route::get('/', function (Intervention\HttpAuth\HttpAuth $httpauth) {
    $httpauth->secure();
    return view('welcome');
});
```

**Comment by edalzell** [comment]
Sorry, noticed that the package I was looking at is using an older version.
